### ISSUE TITLE
Problems installing Chordomics on Windows 10 computers

### ISSUE THREAD

**Issue by zbendiks** [KevinMcDonnell6/chordomics#4]
Hi,

I had some trouble installing Chordomics on two Win10 computers that I recently worked through.  The installation would nearly reach completion every time, but I would get an error message like the one below and the installation would fail: 

```
> devtools::install_github('KevinMcDonnell6/chordomics')

...

package ‘rlang’ successfully unpacked and MD5 sums checked 
Warning: cannot remove prior installation of package ‘rlang’ 
```

The way I got around this was by manually editing the name of the 'rlang' folder within my R v3.6.2 packages directory. In my case, I simply changed the name to 'rlang-bak' and the error message went away.  But I received similar errors and had to manually adjust the folder names for the 'fansi' and 'digest' packages, then the installation finally worked.  

It seems like the way in which Chordomics searches for pre-installed R packages is potentially causing problems.

**Comment by nickp60** [comment]
Hi @zbendiks ,
This looks like a pretty common issue with background processes preventing the deletion of old versions of packages: 
- https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi
- https://support.microsoft.com/en-us/help/3104094/cannot-install-forecast-package-on-revolution-7-1
- https://www.reddit.com/r/Rlanguage/comments/56daco/cant_download_this_r_packagewasted_a_complete_day/

This isn't an issue with Chordomics, more of an issue with Windows and Devtools, so I will close this issue.  Thanks for flagging it though, glad you got it sorted out in the end!
